### ISSUE TITLE
Note to owner - token licensing tool available

### ISSUE THREAD

**Issue by VagruariesOfFate** [adventuremagic123/PF1e-And-3.5-Framework-For-MapTool#3]
I have linked your repo to the RPG Nexus MT Frameworks + database.

If you are interested in adding your license to your tokens, there is a first stage licensing tool in the repo as well.

https://github.com/MT-Tools-Database/Frameworks-plus/

**Comment by adventuremagic123** [comment]
> I have linked your repo to the RPG Nexus MT Frameworks + database.
> 
> If you are interested in adding your license to your tokens, there is a first stage licensing tool in the repo as well.
> 
> https://github.com/MT-Tools-Database/Frameworks-plus/

Thank you for doing that.
